openapi: 3.0.0
info:
  title: Tour API
  version: 1.0.0
  description: API for managing tours

servers:
  - url: /api

paths:
  /tours:
    get:
      summary: Get all tours
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tour'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new tour
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourInput'
      responses:
        '201':
          description: Tour created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tours/{tourId}:
    get:
      summary: Get a tour by ID
      parameters:
        - in: path
          name: tourId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '400':
          description: Invalid tour ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Invalid tour ID"
        '404':
          description: Tour not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Tour not found"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Failed to retrieve tour"

    put:
      summary: Update a tour
      parameters:
        - in: path
          name: tourId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourInput'
            example:
              name: "Updated Tour Name"
              info: "This tour has been updated with new information"
              image: "https://example.com/updated-tour-image.jpg"
              price: "199.99"
      responses:
        '200':
          description: Tour updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '400':
          description: Invalid tour ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Invalid tour ID"
        '404':
          description: Tour not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Tour not found"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Failed to update tour"

    delete:
      summary: Delete a tour
      parameters:
        - in: path
          name: tourId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tour deleted successfully
        '400':
          description: Invalid tour ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Invalid tour ID"
        '404':
          description: Tour not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Tour not found"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Failed to delete tour"

components:
  schemas:
    Tour:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        info:
          type: string
        image:
          type: string
        price:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    TourInput:
      type: object
      required:
        - name
        - info
        - image
        - price
      properties:
        name:
          type: string
        info:
          type: string
        image:
          type: string
        price:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
      example:
        message: "An error occurred"